@url = http://localhost:3033

### simple users READ
GET {{url}}/simpleUsers
content-type: application/json

### simple users CREATE
POST {{url}}/simpleUsers/create
content-type: application/json
 
{
    "firstName": "Andre",
    "lastName": "Hackerkrug"
}
### simple users UPDATE
PATCH {{url}}/simpleUsers/update/619d83eed2fb430e6e4c376a
content-type: application/json
 
{"firstName": "Osama",
    "lastName": "Al Haj Abdullah"
}
### simple users DELETE
DELETE {{url}}/simpleUsers/delete/619d83eed2fb430e6e4c376a
content-type: application/json

### nested users READ
GET {{url}}/nestedUsers
content-type: application/json

### nested users READ
GET {{url}}/nestedUsers/emails
content-type: application/json
### nested users READ
GET {{url}}/nestedUsers/accountHistory/619d7bb7017e9300920ffbd7
content-type: application/json

### nested users CREATE
POST {{url}}/nestedUsers/create
content-type: application/json
 
{
    "name" : "Stephanie Added",
    "username" : "Brandyn_Reilly59",
    "email" : "Tyshawn.Abshire@yahoo.com",
    "address" : {
        "street" : "Hill Parks",
        "suite" : "Suite 582",
        "city" : "Garfieldmouth",
        "zipcode" : "21401-7727"
    },
    "phone" : "502-899-9440 x015",
    "website" : "jessyca.org",
    "company" : "Kshlerin, Wiza and Ferry",
    "accountHistory" : [
        {
            "amount" : 333,
            "date" : "2021-11-15T16:52:26.505+01:00",
            "purchase" : "Fantastic Wooden Table"
        },
        {
            "amount" : 665.01,
            "date" : "2021-11-15T16:52:26.505+01:00",
            "purchase" : "Tasty Soft Towels"
        },
        {
            "amount" : 205.68,
            "date" : "2021-11-15T16:52:26.505+01:00",
            "purchase" : "Small Concrete Chair"
        }
    ]
}

### nested users UPDATE
PATCH {{url}}/nestedUsers/update/619d7bb7017e9300920ffbdb
content-type: application/json
 
{
    "name": "Stephanie Changed",
    "address.street": "changed street",
    "accountHistory.2.amount": 999
}
### nested users DELETE
DELETE  {{url}}/nestedUsers/delete/619e7c2254463215224cb930
content-type: application/json